@echo off
setlocal

call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character01_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character02_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character03_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character04_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character05_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character07_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character08_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character09_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character11_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character12_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character13_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character14_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character15_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character17_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character18_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character19_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character21_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character22_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character23_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character24_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character25_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character27_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character28_NY1"
call :CopyFile "Input\#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character29_NY1"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character01_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character02_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character03_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character04_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character05_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character07_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character08_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character09_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character11_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character12_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character13_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character14_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character15_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character17_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character18_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character19_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character21_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character22_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character23_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character24_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character25_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character27_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character28_NY2"
call :CopyFile "Input\#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character29_NY2"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character01_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character02_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character03_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character04_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character05_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character07_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character08_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character09_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character11_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character12_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character13_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character14_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character15_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character17_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character18_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character19_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character21_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character22_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character23_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character24_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character25_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character27_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character28_NY3"
call :CopyFile "Input\#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character29_NY3"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character01_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character02_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character03_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character04_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character05_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character07_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character08_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character09_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character11_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character12_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character13_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character14_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character15_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character17_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character18_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character19_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character21_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character22_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character23_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character24_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character25_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character27_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character28_NY1"
call :CopyFile "Input\+#ActD_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_Character29_NY1"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character01_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character02_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character03_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character04_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character05_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character07_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character08_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character09_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character11_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character12_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character13_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character14_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character15_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character17_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character18_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character19_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character21_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character22_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character23_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character24_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character25_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character27_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character28_NY2"
call :CopyFile "Input\+#ActD_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_Character29_NY2"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character01_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character02_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character03_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character04_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character05_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character07_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character08_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character09_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character11_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character12_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character13_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character14_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character15_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character17_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character18_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character19_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character21_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character22_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character23_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character24_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character25_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character27_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character28_NY3"
call :CopyFile "Input\+#ActD_SubNY_03\SceneEffect.prm.xml" "Packing\#Sub_Character29_NY3"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
