@echo off
setlocal

call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character01_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character02_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character03_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character04_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character05_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character07_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character08_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character09_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character11_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character12_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character13_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character14_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character15_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character17_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character18_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character19_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character21_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character22_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character23_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character24_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character25_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character27_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character28_Petra2"
call :CopyFile "Input\#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character29_Petra2"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character01_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character02_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character03_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character04_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character05_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character07_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character08_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character09_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character11_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character12_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character13_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character14_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character15_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character17_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character18_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character19_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character21_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character22_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character23_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character24_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character25_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character27_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character28_Petra3"
call :CopyFile "Input\#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character29_Petra3"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character01_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character02_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character03_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character04_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character05_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character07_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character08_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character09_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character11_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character12_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character13_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character14_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character15_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character17_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character18_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character19_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character21_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character22_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character23_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character24_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character25_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character27_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character28_Petra4"
call :CopyFile "Input\#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character29_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character01_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character02_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character03_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character04_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character05_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character07_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character08_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character09_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character11_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character12_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character13_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character14_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character15_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character17_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character18_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character19_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character21_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character22_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character23_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character24_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character25_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character27_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character28_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_Character29_Petra2"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character01_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character02_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character03_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character04_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character05_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character07_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character08_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character09_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character11_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character12_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character13_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character14_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character15_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character17_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character18_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character19_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character21_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character22_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character23_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character24_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character25_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character27_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character28_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_Character29_Petra3"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character01_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character02_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character03_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character04_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character05_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character07_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character08_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character09_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character11_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character12_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character13_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character14_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character15_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character17_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character18_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character19_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character21_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character22_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character23_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character24_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character25_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character27_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character28_Petra4"
call :CopyFile "Input\+#ActD_SubPetra_04\SceneEffect.prm.xml" "Packing\#Sub_Character29_Petra4"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
