@echo off
setlocal

call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character01_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character02_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character03_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character04_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character05_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character07_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character08_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character09_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character11_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character12_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character13_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character14_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character15_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character17_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character18_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character19_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character21_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character22_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character23_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character24_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character25_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character27_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character28_Beetle"
call :CopyFile "Input\#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character29_Beetle"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character01_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character02_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character03_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character04_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character05_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character07_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character08_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character09_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character11_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character12_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character13_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character14_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character15_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character17_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character18_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character19_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character21_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character22_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character23_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character24_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character25_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character27_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character28_Lancer"
call :CopyFile "Input\#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character29_Lancer"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character01_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character02_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character03_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character04_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character05_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character07_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character08_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character09_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character11_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character12_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character13_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character14_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character15_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character17_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character18_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character19_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character21_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character22_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character23_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character24_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character25_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character27_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character28_Ray"
call :CopyFile "Input\#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character29_Ray"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character01_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character02_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character03_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character04_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character05_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character07_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character08_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character09_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character11_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character12_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character13_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character14_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character15_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character17_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character18_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character19_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character21_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character22_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character23_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character24_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character25_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character27_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character28_Beetle"
call :CopyFile "Input\+#BossEggBeetle\SceneEffect.prm.xml" "Packing\#Character29_Beetle"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character01_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character02_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character03_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character04_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character05_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character07_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character08_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character09_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character11_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character12_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character13_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character14_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character15_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character17_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character18_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character19_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character21_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character22_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character23_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character24_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character25_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character27_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character28_Lancer"
call :CopyFile "Input\+#BossEggLancer\SceneEffect.prm.xml" "Packing\#Character29_Lancer"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character01_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character02_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character03_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character04_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character05_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character07_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character08_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character09_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character11_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character12_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character13_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character14_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character15_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character17_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character18_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character19_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character21_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character22_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character23_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character24_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character25_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character27_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character28_Ray"
call :CopyFile "Input\+#BossEggRayBird\SceneEffect.prm.xml" "Packing\#Character29_Ray"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
