@echo off
setlocal

call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_NY1"
call :CopyFile "Input\#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_NY1"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_NY2"
call :CopyFile "Input\#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_NY2"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_NY1"
call :CopyFile "Input\+#ActN_SubNY_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_NY1"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_NY2"
call :CopyFile "Input\+#ActN_SubNY_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_NY2"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
