@echo off
setlocal

call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Petra1"
call :CopyFile "Input\#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Petra1"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Petra2"
call :CopyFile "Input\#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Petra1"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Petra2"
call :CopyFile "Input\+#ActN_SubPetra_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Petra2"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
