@echo off
setlocal

call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Snow1"
call :CopyFile "Input\#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Snow1"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Snow2"
call :CopyFile "Input\#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Snow1"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Snow2"
call :CopyFile "Input\+#ActN_SubSnow_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Snow2"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
