@echo off
setlocal

call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_EU1"
call :CopyFile "Input\#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_EU1"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_EU2"
call :CopyFile "Input\#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_EU2"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_EU1"
call :CopyFile "Input\+#ActN_SubEU_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_EU1"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_EU2"
call :CopyFile "Input\+#ActN_SubEU_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_EU2"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
