@echo off
setlocal

call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Beach1"
call :CopyFile "Input\#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Beach1"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Beach2"
call :CopyFile "Input\#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Beach2"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Beach3"
call :CopyFile "Input\#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Beach1"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Beach2"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Beach3"
call :CopyFile "Input\+#ActN_SubBeach_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Beach3"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
