@echo off
setlocal

call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Africa1"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Africa2"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Africa3"
call :CopyFile "Input\#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Africa1"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Africa2"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Africa3"
call :CopyFile "Input\+#ActN_SubAfrica_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Africa3"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
