@echo off
setlocal

call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Mykonos1"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Mykonos2"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Mykonos3"
call :CopyFile "Input\#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Mykonos1"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_04\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Mykonos2"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_Mykonos3"
call :CopyFile "Input\+#ActN_SubMykonos_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_Mykonos3"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
