@echo off
setlocal

call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_China1"
call :CopyFile "Input\#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_China1"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_China2"
call :CopyFile "Input\#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_China2"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_China3"
call :CopyFile "Input\#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_China3"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_China1"
call :CopyFile "Input\+#ActN_SubChina_01\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_China1"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_China2"
call :CopyFile "Input\+#ActN_SubChina_02\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_China2"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter01_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter02_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter03_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter04_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter05_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter07_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter08_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter09_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter11_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter12_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter13_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter14_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter15_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter17_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter18_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter19_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter21_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter22_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter23_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter24_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter25_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter27_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter28_China3"
call :CopyFile "Input\+#ActN_SubChina_03\SceneEffect.prm.xml" "Packing\#Sub_EvilCharacter29_China3"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
