@echo off
setlocal

call :CopyFile "Input\#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Rush_Africa"
call :CopyFile "Input\#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Brawler_Africa"
call :CopyFile "Input\#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Beast_Africa"
call :CopyFile "Input\#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Legend_Africa"
call :CopyFile "Input\#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Reborn_Africa"
call :CopyFile "Input\#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Africa"
call :CopyFile "Input\#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Rush_EU"
call :CopyFile "Input\#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Brawler_EU"
call :CopyFile "Input\#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Beast_EU"
call :CopyFile "Input\#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Legend_EU"
call :CopyFile "Input\#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Reborn_EU"
call :CopyFile "Input\#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_EU"
call :CopyFile "Input\#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Rush_Mykonos"
call :CopyFile "Input\#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Brawler_Mykonos"
call :CopyFile "Input\#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Beast_Mykonos"
call :CopyFile "Input\#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Legend_Mykonos"
call :CopyFile "Input\#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Reborn_Mykonos"
call :CopyFile "Input\#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Mykonos"
call :CopyFile "Input\#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Rush_NY"
call :CopyFile "Input\#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Brawler_NY"
call :CopyFile "Input\#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Beast_NY"
call :CopyFile "Input\#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Legend_NY"
call :CopyFile "Input\#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Reborn_NY"
call :CopyFile "Input\#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_NY"
call :CopyFile "Input\#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Rush_Petra"
call :CopyFile "Input\#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Brawler_Petra"
call :CopyFile "Input\#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Beast_Petra"
call :CopyFile "Input\#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Legend_Petra"
call :CopyFile "Input\#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Reborn_Petra"
call :CopyFile "Input\#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Petra"
call :CopyFile "Input\#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Rush_Beach"
call :CopyFile "Input\#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Brawler_Beach"
call :CopyFile "Input\#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Beast_Beach"
call :CopyFile "Input\#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Legend_Beach"
call :CopyFile "Input\#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Reborn_Beach"
call :CopyFile "Input\#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Beach"
call :CopyFile "Input\#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Rush_China"
call :CopyFile "Input\#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Brawler_China"
call :CopyFile "Input\#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Beast_China"
call :CopyFile "Input\#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Legend_China"
call :CopyFile "Input\#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Reborn_China"
call :CopyFile "Input\#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_China"
call :CopyFile "Input\#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Rush_Snow"
call :CopyFile "Input\#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Brawler_Snow"
call :CopyFile "Input\#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Beast_Snow"
call :CopyFile "Input\#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Legend_Snow"
call :CopyFile "Input\#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Reborn_Snow"
call :CopyFile "Input\#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Snow"
call :CopyFile "Input\+#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Rush_Africa"
call :CopyFile "Input\+#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Brawler_Africa"
call :CopyFile "Input\+#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Beast_Africa"
call :CopyFile "Input\+#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Legend_Africa"
call :CopyFile "Input\+#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#Reborn_Africa"
call :CopyFile "Input\+#ActN_AfricaEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Africa"
call :CopyFile "Input\+#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Rush_EU"
call :CopyFile "Input\+#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Brawler_EU"
call :CopyFile "Input\+#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Beast_EU"
call :CopyFile "Input\+#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Legend_EU"
call :CopyFile "Input\+#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#Reborn_EU"
call :CopyFile "Input\+#ActN_EUEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_EU"
call :CopyFile "Input\+#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Rush_Mykonos"
call :CopyFile "Input\+#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Brawler_Mykonos"
call :CopyFile "Input\+#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Beast_Mykonos"
call :CopyFile "Input\+#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Legend_Mykonos"
call :CopyFile "Input\+#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#Reborn_Mykonos"
call :CopyFile "Input\+#ActN_MykonosEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Mykonos"
call :CopyFile "Input\+#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Brawler_NY"
call :CopyFile "Input\+#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Beast_NY"
call :CopyFile "Input\+#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Legend_NY"
call :CopyFile "Input\+#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#Reborn_NY"
call :CopyFile "Input\+#ActN_NYEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_NY"
call :CopyFile "Input\+#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Rush_Petra"
call :CopyFile "Input\+#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Brawler_Petra"
call :CopyFile "Input\+#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Beast_Petra"
call :CopyFile "Input\+#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Legend_Petra"
call :CopyFile "Input\+#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#Reborn_Petra"
call :CopyFile "Input\+#ActN_PetraEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Petra"
call :CopyFile "Input\+#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Rush_Beach"
call :CopyFile "Input\+#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Brawler_Beach"
call :CopyFile "Input\+#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Beast_Beach"
call :CopyFile "Input\+#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Legend_Beach"
call :CopyFile "Input\+#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#Reborn_Beach"
call :CopyFile "Input\+#ActN_BeachEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Beach"
call :CopyFile "Input\+#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Rush_China"
call :CopyFile "Input\+#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Brawler_China"
call :CopyFile "Input\+#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Beast_China"
call :CopyFile "Input\+#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Legend_China"
call :CopyFile "Input\+#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#Reborn_China"
call :CopyFile "Input\+#ActN_ChinaEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_China"
call :CopyFile "Input\+#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Rush_Snow"
call :CopyFile "Input\+#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Brawler_Snow"
call :CopyFile "Input\+#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Beast_Snow"
call :CopyFile "Input\+#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Legend_Snow"
call :CopyFile "Input\+#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#Reborn_Snow"
call :CopyFile "Input\+#ActN_SnowEvil\SceneEffect.prm.xml" "Packing\#HedgehogMayCry_Snow"

echo All transfers completed!
pause
exit /b

:CopyFile
set "SRC_FILE=%~dp0%~1"
set "DEST_FOLDER=%~dp0%~2"

if not exist "%DEST_FOLDER%" mkdir "%DEST_FOLDER%"

copy "%SRC_FILE%" "%DEST_FOLDER%" >nul

if %errorlevel% equ 0 (
    echo Copied "%SRC_FILE%" to "%DEST_FOLDER%"
) else (
    echo Failed to copy "%SRC_FILE%"!
)
exit /b
